name: Run Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:

jobs:
  init:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install sedge
        run: |
          curl -L https://github.com/NethermindEth/sedge/releases/download/v1.3.2/sedge-v1.3.2-linux-amd64 --output sedge
          chmod +x ./sedge

      - name: Install NPM dependencies
        run: npm ci

      - name: Cache DB
        id: cache-db
        uses: actions/cache@v4
        with:
          path: |
            consensus-data
            execution-dat
          key: ${{ runner.os }}-eth-${{ github.run_id }}
          restore-keys: ${{ runner.os }}-eth

      - name: Start sedge
        run: |
          ./scripts/run-sedge.sh

      - name: Wait for full sync
        run: |
          npx ts-node ./scripts/waitForFullSync.ts

  tests:
    needs: [init]
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Run tests
        run: |
          npm run test

  clean-up:
    needs: [init, tests]
    runs-on: ubuntu-latest
    timeout-minutes: 15
    if: ${{ always() }}
    steps:
      - name: Show docker logs
        if: always()
        run: |
          docker ps -q | xargs -L 1 docker logs

      - name: Stop sedge
        if: always()
        run: |
          ./sedge -p $PWD down

      - name: Fix permissions before caching
        if: always()
        run: |
          sudo chmod -R a+r consensus-data     
          sudo chmod -R a+r execution-data
